# Generated by Django 5.0.1 on 2024-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('nationality_name', models.CharField(max_length=40)),
                ('flag', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=100)),
                ('currency_sign', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=4)),
                ('listed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
