# Generated by Django 5.0.1 on 2024-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_feature',
            field=models.ManyToManyField(to='be_api_members.planfeature'),
        ),
    ]
