# Generated by Django 5.0.1 on 2024-01-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.OneToOneField(default=837, on_delete=django.db.models.deletion.DO_NOTHING, to='be_api_members.country'),
        ),
    ]
