# Generated by Django 5.0.1 on 2024-01-18 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0002_alter_profile_nationality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='organization',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.OneToOneField(default=837, on_delete=django.db.models.deletion.DO_NOTHING, to='be_api_members.country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='interests',
            field=models.CharField(choices=[('1', 'Organization & Effectiveness'), ('2', 'Projects & Construction'), ('3', 'Banking & Finance'), ('4', 'Hospitality, Leisure & Tourism'), ('5', 'ICT'), ('6', 'Legal'), ('7', 'Women in Business'), ('8', 'Young Professionals')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='martial',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default=''),
        ),
    ]
