# Generated by Django 5.0.1 on 2024-01-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0002_planfeature_remove_plan_features_plan_plan_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be_api_members.organization'),
        ),
    ]
