# Generated by Django 5.0.1 on 2024-01-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Not Active')], default='0', max_length=1),
        ),
    ]
