# Generated by Django 5.0.1 on 2024-01-18 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0004_remove_organization_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('member_number', models.IntegerField()),
                ('features', models.CharField(choices=[('B', 'Benefits'), ('E', 'Events'), ('N', 'Newsletters')], default='B', max_length=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
