# Generated by Django 4.2.9 on 2024-01-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be_api_members', '0005_plan_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='', upload_to='fs_business_mvt/static/uploads'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_api_members.organization', unique=True)),
                ('used_by_user', models.ManyToManyField(blank=True, related_name='used_benefit', to='be_api_members.profile')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_feature',
            field=models.ManyToManyField(to='be_api_members.planfeature'),
        ),
    ]
